### ISSUE TITLE
Traffic?

### ISSUE THREAD

**Issue by withoutboats** [withoutboats/notty#16]
I notice this repo has had a bit of a traffic spike today, but in the info GitHub provides me, I can't find a novel source of traffic that could explain it. If anyone comes across this and knows what's up, I'd like to know. :smile: I love answering questions about this project and its goals, and I know its not in a state which speaks for itself just yet.

**Comment by dylanaraps** [comment]
It was posted on /r/linux yesterday.

https://www.reddit.com/r/linux/comments/461aet/notty_a_new_kind_of_terminal/

**Comment by withoutboats** [comment]
Thanks!
