### ISSUE TITLE
compiling on 32 bit system

### ISSUE THREAD

**Issue by timb** [withoutboats/notty#18]
I was able to build and run the demo terminal by changing [line 25 in image_renderer.rs](https://github.com/withoutboats/notty/blob/master/notty-cairo/src/image_renderer.rs#L25) from 
'as i64' to 'as i32'. 

I know very little about Rust... possible to automatically infer that type?

**Comment by withoutboats** [comment]
In idiomatic Rust this value would be an `isize`, but because this is C FFI its a library defined type that is a different size on different systems. I'll have a patch up that fixes this in a few minutes.

**Comment by withoutboats** [comment]
Can you pull the `support_32bit_systems` branch and confirm that it compiles and runs for you? Once I have that confirmation I'll merge the change in.

**Comment by timb** [comment]
Nice, that works. Thanks!

(I had got as far as trying out `isize` and `libc::ssize_t` but didn't figure out that `extern crate libc;` was necessary in `notty-cairo/src/lib.rs`  )
