### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by SolarAquarion** [withoutboats/notty#51]
running 2 tests
test cfg::toml::tests::test_default ... FAILED
test cfg::toml::tests::test_update_from_file ... FAILED

failures:

---- cfg::toml::tests::test_default stdout ----
    thread 'cfg::toml::tests::test_default' panicked at 'assertion failed: `(left == right)` (left: `"Monospace 10"`, right: `"Inconsolata 10"`)', src/cfg/toml.rs:244
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- cfg::toml::tests::test_update_from_file stdout ----
    thread 'cfg::toml::tests::test_update_from_file' panicked at 'assertion failed: `(left == right)` (left: `"Monospace 10"`, right: `"Inconsolata 10"`)', src/cfg/toml.rs:244

failures:
    cfg::toml::tests::test_default
    cfg::toml::tests::test_update_from_file

**Comment by SolarAquarion** [comment]
inconosolata is a dependency?

**Comment by SolarAquarion** [comment]
no fails

**Comment by withoutboats** [comment]
I changed the default without changing the spec, I'll check in a fix tonight. (the point of the change was that inconsolata should not be a dependency)
