### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by bmcorser** [withoutboats/notty#7]
Looks like a really interesting project, it would be great to see some installation instructions.

**Comment by withoutboats** [comment]
Unfortunately, this project isn't in a usable state yet. Its actually a library for parsing tty output and managing the internal state machine of the terminal; hopefully it will be the basis for multiple applications.

If you have all the dependencies for the scaffolding terminal (I think just GTK, pango & cairo) on a UNIX system, the scaffolding terminal should be buildable using the nightly version of Rust's project manager `cargo`. But scaffolding is buggy, not featureful, and not intended for every day use.

**Comment by blakesweeney** [comment]
Just a small note, but I tried to build the scaffolding recently and ran into a bug in the rust compiler. I'm pretty sure it is [this](https://github.com/rust-lang/rust/issues/29857) issue. Though the linked issue in [glib](https://github.com/gtk-rs/glib/issues/76) says this bug shouldn't be an issue anymore. So you might have some troubles getting the scaffolding to work.

**Comment by bmcorser** [comment]
OK, I'll close this issue but keep my eyes open!

**Comment by withoutboats** [comment]
@blakesweeney sorry it took two weeks, but I've gotten around to triaging the issue you mentioned and its just that the gtk dependencies needed to have their versions bumped. The current commit fixes it.

**Comment by blakesweeney** [comment]
Thanks for looking into this. I'm interested in seeing where this project goes!

**Comment by withoutboats** [comment]
For sure. :smile: I'm working on getting the scaffolding terminal to render images, hopefully by the new year!

**Comment by alok** [comment]
is this in a usable state yet?
